server:
  port: 8002
spring:
  boot:
    admin:
      username: yangwensheng
      password: 123456
  redis:
    host: 140.143.0.126
    password: 123456
    port: 6379
    database: 0
    pool:
      max-idle: 8
      max-wait: 1
    timeout: 0
  session:
    store-type: none
eureka:
  instance:
    hostname: spring-cloud-discovery
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://yangwensheng:${REGISTRY_SERVER_PASSWORD:123456}@spring-cloud-discovery:8761/eureka/
#mybatis配置
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.xingling.cloud.model.domain
#通用mapper配置
mapper:
  mappers: com.xingling.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
env:
#rocketMq配置
rocketMq:
  default-producer-grouop-name: ProducerGroup
  transaction-producer-group-name: transactionProducerGroupName
  namesrvAddr: 192.168.32.246:9876
  instanceName: testProducer
  maxMessageSize: 131072
  sendMsgTimeout: 10000
  topic: testTopic
  tag: testTag
  consume-thread-max: 64
  consume-thread-min: 20
logging:
    level:
        com.xingling.cloud.mapper: DEBUG
        org.springframework.security: DEBUG
    pattern:
      level:
management:
  security:
    enabled: false
security:
  user:
    name: yangwensheng
    password: 123456
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: ${security.user.password}
      access-token-uri: http://spring-cloud-gateway:8030/umc/oauth/token
      user-authorization-uri: http://spring-cloud-gateway:8030/umc/oauth/authorize
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://spring-cloud-provider-user:8000/user/currentUser
      prefer-token-info: false
#查看info信息配置
info:
  app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  owner: 190332447@qq.com
  url: http://localhost:${server.port}/