server:
  port: 8000
spring:
  boot:
    admin:
      username: yangwensheng
      password: 123456
  redis:
    host: 140.143.0.126
    password: 123456
    port: 6379
    database: 0
    pool:
      max-idle: 8
      max-wait: 1
    timeout: 0
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
       username: admin
       password: 123456
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://140.143.0.126:3306/xingling_umc
# Email (MailProperties)
  mail:
    host:
    username: 190332447@qq.com
    password: 13718891700
    default-encoding: utf-8
    port: 25
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          quitwait: false
      transport:
          protocol: smtps
eureka:
  instance:
    hostname: spring-cloud-discovery
    prefer-ip-address: true
    statusPageUrlPath: /login
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://yangwensheng:${REGISTRY_SERVER_PASSWORD:123456}@spring-cloud-discovery:8761/eureka/
#多数据愿读写分离配置
#customerDataSource:
#  master:
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/xingling_umc?characterEncoding=UTF-8
#  slaver:
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    jdbc-url: jdbc:mysql://localhost:3306/xingling_umc1?characterEncoding=UTF-8
#  read: get,select,count,list,query
#  write: add,create,update,delete,remove,insert,batchSave,batchUpdate,batchDelete
#rocketMq配置
rocketMq:
  default-producer-grouop-name: ProducerGroup
  transaction-producer-group-name: transactionProducerGroupName
  namesrvAddr: 140.143.0.126:9876
  instanceName: testProducer
  maxMessageSize: 131072
  sendMsgTimeout: 10000
  topic: testTopic
  tag: testTag
  consume-thread-max: 64
  consume-thread-min: 20
#mybatis配置
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.xingling.cloud.model.domain
#通用mapper配置
mapper:
  mappers: com.xingling.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
security:
  oauth2:
    resource:
      filter-order: 3
logging:
    level:
        com.xingling.cloud.mapper: DEBUG
        org.springframework.security: DEBUG
    pattern:
      level:
#查看info信息配置
info:
  app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
  owner: 190332447@qq.com
  url: http://${spring.cloud.client.ipAddress}:${server.port}/login
#swagger配置
swagger:
  description: 用户微服务