server:
  port: 8020
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xinglinglove/spring-cloud-koala
          search-paths: config-repo
          username: 190332447@qq.com
          password: 13718891700
  rabbitmq:
    host: spring-cloud-rabbitmq
    username: yangwensheng
    password: 123456
eureka:
  instance:
    hostname: spring-cloud-discovery
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://yangwensheng:${REGISTRY_SERVER_PASSWORD:123456}@spring-cloud-discovery:8761/eureka/
security:
  user:
    name: yangwensheng
    password: ${CONFIG_SERVER_PASSWORD:123456}