server:
  port: 8050
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8010
      username: yangwensheng
      password: 123456
  datasource:
    url: jdbc:mysql://140.143.0.126:3306/xingling_zipkin?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 140.143.0.126
    password: 123456
    port: 6379
    database: 0
    pool:
      max-idle: 8
      max-wait: 1
    timeout: 0
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://yangwensheng:123456@spring-cloud-discovery:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
zipkin:
  storage:
    type: mysql
management:
  security:
    enabled: false
info:
  owner: 19033247@qq.com
  version: @project.version@